### ISSUE TITLE
Property 'auth' does not exist on type 'AngularFireAuth'.

### ISSUE THREAD

**Issue by iamAbdulla** [SinghDigamber/angularfirebase-authentication#8]

**Comment by iamAbdulla** [comment]
error TS2339: Property 'auth' does not exist on type 'AngularFireAuth'.

**Comment by YassineBaggar** [comment]
just delete 'auth' like 'this.afAuth.signInWithEmailAndPassword(email, password)' and it will be work

**Comment by IMSRIJAN04** [comment]
GoogleAuth() {
    return this.AuthLogin(new auth.GoogleAuthProvider());
  }
how can i remove auth here
if removed its unable to find .GoogleAuthProvider()
please help me out here

**Comment by IMSRIJAN04** [comment]
yeah! it got resolved by replacing firebase.auth

**Comment by KrutarthChovatiya** [comment]
@YassineBaggar  I have deleted auth it's working but still isn't working with send email verification otherwise it's working fine.
Can you help me with this ?

**Comment by IMSRIJAN04** [comment]
Can you tell me the issue in detail so that I may try to help you out

**Comment by KrutarthChovatiya** [comment]
@IMSRIJAN04  I have removed auth from signing signup also used firebase.auth.GoogleAuthProvider() and it all worked but removing auth from sendemailverification isn't working

**Comment by mehmoodulhaq** [comment]
Please use
import firebase from 'firebase';
and in service 
// Sign in with Google
  GoogleAuth() {

    return this.AuthLogin(new firebase.auth.GoogleAuthProvider());
  }
  FacebookAuth() {

    return this.AuthLogin(new firebase.auth.FacebookAuthProvider());
  }

**Comment by AlexanderDH10** [comment]
###  Hi, I have solved this bug based on another repository.

First step: Open `auth.service.ts` and remove the line
```javascript
//import { auth } from 'firebase/app';
```

Second step: import firebase
```javascript
import firebase from 'firebase';
```

Third step: Update the following lines

**Old way:**
```javascript
SignIn(email, password) {
   return this.afAuth.auth.signInWithEmailAndPassword(email, password)
 .then((result) => {
        this.ngZone.run(() => {
          this.router.navigate(['dashboard']);
        });
        this.SetUserData(result.user);
      }).catch((error) => {
        window.alert(error.message)
      })
  }
```
**New way:**
```javascript
SignIn(email, password) {
   return this.afAuth.signInWithEmailAndPassword(email, password) //Only remove auth
 .then((result) => {
        this.ngZone.run(() => {
          this.router.navigate(['dashboard']);
        });
        this.SetUserData(result.user);
      }).catch((error) => {
        window.alert(error.message)
      })
  }
```
**Old way:**
```javascript


 SignUp(email, password) {
    return this.afAuth.auth.createUserWithEmailAndPassword(email, password)
      .then((result) => {
        /* Call the SendVerificaitonMail() function when new user sign 
        up and returns promise */
        this.SendVerificationMail();
        this.SetUserData(result.user);
      }).catch((error) => {
        window.alert(error.message)
      })
  }
```
**New way:**
```javascript
SignUp(email, password) {
    return this.afAuth.createUserWithEmailAndPassword(email, password) //Only remove auth
      .then((result) => {
        /* Call the SendVerificaitonMail() function when new user sign 
        up and returns promise */
        this.SendVerificationMail();
        this.SetUserData(result.user);
      }).catch((error) => {
        window.alert(error.message)
      })
  }
```
**Old way:**
```javascript
 SendVerificationMail() {
    return this.afAuth.auth.currentUser.sendEmailVerification()
    .then(() => {
      this.router.navigate(['verify-email-address']);
    })
  }
```
**New way:**
```javascript
//add async/await and remove auth
async SendVerificationMail() {
    return await(await this.afAuth.currentUser).sendEmailVerification()
    .then(() => {
      this.router.navigate(['verify-email-address']);
    })
  }
```
**Old way:**
```javascript
 ForgotPassword(passwordResetEmail) {
    return this.afAuth.auth.sendPasswordResetEmail(passwordResetEmail)
    .then(() => {
      window.alert('Password reset email sent, check your inbox.');
    }).catch((error) => {
      window.alert(error)
    })
  }
```
**New way:**
```javascript
 ForgotPassword(passwordResetEmail) {
    return this.afAuth.sendPasswordResetEmail(passwordResetEmail)//remove auth
    .then(() => {
      window.alert('Password reset email sent, check your inbox.');
    }).catch((error) => {
      window.alert(error)
    })
  }
```
**Old way:**
```javascript
GoogleAuth() {
    return this.AuthLogin(new auth.GoogleAuthProvider());
  }
```
**New way:**
```javascript
GoogleAuth() {
    return this.AuthLogin(new firebase.auth.GoogleAuthProvider()); //add firebase
  }
```
Greetings from Mexico.
